-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 15:32:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cardapio` (
  `pkid_cardapio` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pkid_cardapio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_gerente` (
  `pkid_gerente` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pkid_gerente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_garcom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_garcom` (
  `pkid_garcom` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `fkid_gerente` BIGINT NOT NULL,
  `fkid_cardapio` BIGINT NOT NULL,
  PRIMARY KEY (`pkid_garcom`),
  INDEX `fkid_gerente` (`fkid_gerente` ASC) VISIBLE,
  INDEX `fkid_cardapio` (`fkid_cardapio` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fkid_gerente`
    FOREIGN KEY (`fkid_gerente`)
    REFERENCES `mydb`.`tb_gerente` (`pkid_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkid_cardapio`
    FOREIGN KEY (`fkid_cardapio`)
    REFERENCES `mydb`.`tb_cardapio` (`pkid_cardapio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cozinha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cozinha` (
  `pkid_cozinha` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `fkid_gerente` BIGINT NOT NULL,
  PRIMARY KEY (`pkid_cozinha`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fkid_gerente` (`fkid_gerente` ASC) VISIBLE,
  CONSTRAINT `fkid_gerente`
    FOREIGN KEY (`fkid_gerente`)
    REFERENCES `mydb`.`tb_gerente` (`pkid_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pedido` (
  `pkid_pedido` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `numero_mesa` INT NOT NULL,
  `status_pedido` VARCHAR(45) NOT NULL,
  `fkid_cardapio` BIGINT NOT NULL,
  `fkid_garcom` BIGINT NOT NULL,
  `fkid_cozinha` BIGINT NOT NULL,
  PRIMARY KEY (`pkid_pedido`),
  INDEX `fkid_cardapio` (`fkid_cardapio` ASC) VISIBLE,
  INDEX `fkid_garcom` (`fkid_garcom` ASC) VISIBLE,
  INDEX `fkid_cozinha` (`fkid_cozinha` ASC) VISIBLE,
  CONSTRAINT `fkid_cardapio`
    FOREIGN KEY (`fkid_cardapio`)
    REFERENCES `mydb`.`tb_cardapio` (`pkid_cardapio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkid_garcom`
    FOREIGN KEY (`fkid_garcom`)
    REFERENCES `mydb`.`tb_garcom` (`pkid_garcom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkid_cozinha`
    FOREIGN KEY (`fkid_cozinha`)
    REFERENCES `mydb`.`tb_cozinha` (`pkid_cozinha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_limpeza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_limpeza` (
  `pkid_limpeza` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `fkid_gerente` BIGINT NOT NULL,
  PRIMARY KEY (`pkid_limpeza`),
  INDEX `fkid_gerente` (`fkid_gerente` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fkid_gerente`
    FOREIGN KEY (`fkid_gerente`)
    REFERENCES `mydb`.`tb_gerente` (`pkid_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_estoque` (
  `pkid_estoque` INT NOT NULL AUTO_INCREMENT,
  `quantidade_estoque` INT NOT NULL,
  `mercadoria` VARCHAR(45) NOT NULL,
  `fkid_gerente` BIGINT NOT NULL,
  `fkid_cozinha` BIGINT NOT NULL,
  PRIMARY KEY (`pkid_estoque`),
  INDEX `fkid_gerente` (`fkid_gerente` ASC) VISIBLE,
  INDEX `fkid_cozinha` (`fkid_cozinha` ASC) VISIBLE,
  CONSTRAINT `fkid_gerente`
    FOREIGN KEY (`fkid_gerente`)
    REFERENCES `mydb`.`tb_gerente` (`pkid_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkid_cozinha`
    FOREIGN KEY (`fkid_cozinha`)
    REFERENCES `mydb`.`tb_cozinha` (`pkid_cozinha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
